name: pr-comment

on:
  workflow_run:
    workflows:
      - nf-core linting
      - nf-core template version comment
    types: [completed]

permissions: {}

jobs:
  post-comment:
    permissions:
      actions: read
      pull-requests: write
    uses: nf-core/actions/.github/workflows/pr-comment.yml@v1
