source("assets/report/report-downloads.R")
directory <- tempfile("report-downloads-")
dir.create(directory)
source <- file.path(directory, "bytes.pgen")
original <- as.raw(rep(0:255, 9L))
writeBin(original, source)
metadata <- reportDOWNLOADFILE(source, "downloads/bytes.pgen", directory, chunk_bytes = 511L)
stopifnot(metadata$bytes == length(original), metadata$chunks == 5L)
restored <- raw()
for (number in seq_len(metadata$chunks)) {
  path <- file.path(directory, metadata$base, sprintf("%06d.js", number))
  encoded <- sub('";$', '', sub('^document.currentScript.downloadBytes="', '', readLines(path)))
  restored <- c(restored, openssl::base64_decode(encoded))
}
stopifnot(identical(original, restored), identical(readBin(source, "raw", n = length(original)), original))
writeBin(raw(), source)
empty <- reportDOWNLOADFILE(source, "downloads/empty.pgen", directory)
stopifnot(empty$bytes == 0, empty$chunks == 0)
message("Offline download assets passed: exact bytes, chunk boundaries and empty files.")
